site_name: 'CaseSharing Spec（開発中）'

theme:
  name: readthedocs
  locale: ja

nav:
  - CaseSharing Specについて: /
  - 全体構成:
    - 画面仕様: 'overall-structure/screen-specifications'
  - Cases:
    - 画面仕様: 'cases/screen-specifications'
    - 項目: 'cases/items'
    - 操作:
      - キーワード検索: 'cases/operations/search-keyword'
      - 項目追加: 'cases/operations/add-items'
      - 症例追加: 'cases/operations/add-case'
      - 列の操作: 'cases/operations/operation-column'
      - その他: 'cases/operations/other'
    - 編集:
      - 症例基本情報:
        - 概要: 'cases/edit/case-basic-information'
        - ID: 'cases/edit/case-basic-information#id'
        - 基本情報: 'cases/edit/case-basic-information#basic'
        - 民族・出生地: 'cases/edit/case-basic-information#etnicity'
        - 出生時: 'cases/edit/case-basic-information#birth'
        - 生殖補助: 'cases/edit/case-basic-information#assisted'
        - 入力者情報: 'cases/edit/case-basic-information#inputter'
      - 診療:
        - 概要: 'cases/edit/medical'
        - 詳細:
          - 病歴・生活歴: 'cases/edit/medical#medical-and-life-history'
          - 身体情報・所見: 'cases/edit/medical#physical-information-and-findings'
          - 常用薬・アレルギー・嗜好品: 'cases/edit/medical#regular-medications-allergies-preferences'
          - 疑い病名: 'cases/edit/medical#suspected-case'
          - 遺伝性疾患と考える根拠: 'cases/edit/medical#rationale-for-considering-it-a-genetic-disease'
          - 診断: 'cases/edit/medical#diagnosis'
          - 指定難病: 'cases/edit/medical#designated-incurable-disease'
          - 小児慢性特定疾病: 'cases/edit/medical#chronic-childhood-diseases'
      - 表現型:
        - 概要: 'cases/edit/phenotype'
        - 詳細:
          - 臨床症状: 'cases/edit/phenotype#clinical-symptom'
          - 遺伝型: 'cases/edit/phenotype#genotype'
      - 遺伝型:
        - 概要: 'cases/edit/genotype'
        - 詳細:
          - 検査について: 'cases/edit/genotype#about-testing'
          - 検査結果: 'cases/edit/genotype#testing-result'
          - 結果詳細: 'cases/edit/genotype#details-of-result'
      - 家系:
        - 概要: 'cases/edit/family-info'
        - 家族歴: 'cases/edit/family-info#family-history'
        - 遺伝形式: 'cases/edit/family-info#mode-of-inheritance'
        - 親族（がん・生活習慣病）: 'cases/edit/family-info#relatives'
        - 民族: 'cases/edit/family-info#ethnicity'
        - 近親婚: 'cases/edit/family-info#consanguinity'
        - 家系図: 'cases/edit/family-info#pedigree'
      - 検体・検査:
        - 概要: 'cases/edit/sample-info'
        - 検体採取: 'cases/edit/sample-info#sample-collection'
        - 血液検査等: 'cases/edit/sample-info#blood-test'
        - その他検査: 'cases/edit/sample-info#other-test'
      - 登録:
        - 概要: 'cases/edit/registration'
        - 患者について: 'cases/edit/registration#patient-info'
        - 同意書・アセント: 'cases/edit/registration#consent-ascent'
      - 翻訳:
        - 概要: 'cases/edit/translate'
        - 詳細:
          - 症例基本情報: 'cases/edit/translate#case-basic-information'
          - 診療: 'cases/edit/translate#medical'
          - 表現型: 'cases/edit/translate#phenotype'
          - 遺伝型: 'cases/edit/translate#genotype'
          - 家系: 'cases/edit/translate#family-info'
          - 検体・検査: 'cases/edit/translate#sample-info'
          - 登録: 'cases/edit/translate#registration'
          - その他: 'cases/edit/translate#other'
  - Stats:
    - 画面仕様: 'stats/screen-specifications'
    - 年齢: 'stats/age'
    - 性別: 'stats/gender'
    - グループ名: 'stats/group-name'
    - 症状: 'stats/symptoms'
  - File open:
    - 仕様: 'file-open/specifications'
  - File save:
    - 仕様: 'file-save/specifications'
  - File merge:
    - 仕様: 'file-merge/specifications'

extra_css:
  - assets/css/custom.css
  - assets/css/override.css

markdown_extensions:
  - attr_list
