site_name: "PubCaseFinder Spec"

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Cases:
    - 表:
      - 項目説明: 'docs/cases/table/column.md'
      - 表操作: 'docs/cases/table/column.md'
      - 項目追加: 'docs/cases/table/column.md'
      - キーワード検索: 'docs/cases/table/column.md'
    - 編集:
      - 症例基本情報: 'cases/edit/basicInfo.md'
      - 診療: 'docs/cases/edit/basicInfo.md'
      - 表現型: 'docs/cases/edit/basicInfo.md'
      - 遺伝型: 'docs/cases/edit/basicInfo.md'
      - 家系: 'docs/cases/edit/basicInfo.md'
      - 検体・検査: 'docs/cases/edit/basicInfo.md'
      - 登録: 'docs/cases/edit/basicInfo.md'
  - Stats:
    - 統計情報: 'docs/cases/edit/basicInfo.md'
    - 各グラフ: 'docs/cases/edit/basicInfo.md'
extra_css:
  - css/extra.css
